dependencies:
  # - <org/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  default: ganache-local
  rinkbey:
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    verify: True
  private: 
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False